"use client";
import { useState } from "react";
import { Activity,AlertCircle,ArrowRight,CheckCircle2,Mail } from "lucide-react";
import { createAccount,hasFirebaseConfig,resendVerification,sendPasswordReset,signIn } from "@/lib/firebase-auth";

export function AuthPanel(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"login"|"signup"|"reset">("login"),[message,setMessage]=useState(""),[success,setSuccess]=useState(false),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(!hasFirebaseConfig){setMessage("Add the Firebase environment variables in Vercel first.");return}setBusy(true);setMessage("");setSuccess(false);try{if(mode==="reset"){await sendPasswordReset(email);setMessage("Password-reset email sent. Check your inbox.");setSuccess(true)}else if(mode==="signup"){await createAccount(email,password);setMessage("Account created. We sent a verification link to your email.");setSuccess(true)}else{const session=await signIn(email,password);if(!session.emailVerified){setMessage("Please verify your email before continuing. You can resend the verification link below.")}else location.href="/dashboard"}}catch(error){setMessage(error instanceof Error?error.message:"Authentication failed.")}finally{setBusy(false)}}
 async function resend(){setBusy(true);try{await resendVerification();setMessage("A new verification email has been sent.");setSuccess(true)}catch(error){setMessage(error instanceof Error?error.message:"Could not resend verification.")}finally{setBusy(false)}}
 const heading=mode==="login"?"Sign in":mode==="signup"?"Create your account":"Reset your password";
 return <main className="auth-page"><section className="auth-brand"><a className="brand" href="/"><span><Activity/></span>Prometric <b>Edge</b></a><div><span className="eyebrow">Welcome to your study plan</span><h1>Every session should move you closer to readiness.</h1><p>Save progress, identify weak topics and continue preparing with your verified account.</p></div></section><section className="auth-form"><div><h2>{heading}</h2><p>{mode==="login"?"Continue your exam preparation.":mode==="signup"?"Start with free practice—no card required.":"We will email you a secure password-reset link."}</p>{!hasFirebaseConfig&&<div className="config-alert"><AlertCircle/><span><b>Firebase setup required</b>Add the public Firebase web configuration in Vercel.</span></div>}<form onSubmit={submit}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label>{mode!=="reset"&&<label>Password<input type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" autoComplete={mode==="login"?"current-password":"new-password"}/></label>}{message&&<div className={`form-message ${success?"success":""}`}>{success?<CheckCircle2/>:<AlertCircle/>}<span>{message}</span></div>}<button className="primary-button" disabled={busy}>{busy?"Please wait...":mode==="login"?"Sign in":mode==="signup"?"Create account":"Send reset email"}<ArrowRight size={18}/></button></form>{mode==="login"&&message.includes("verify")&&<button className="resend-button" onClick={resend} disabled={busy}><Mail/>Resend verification email</button>}<div className="auth-links">{mode!=="login"&&<button onClick={()=>{setMode("login");setMessage("")}}>Back to sign in</button>}{mode==="login"&&<><button onClick={()=>{setMode("signup");setMessage("")}}>Create an account</button><button onClick={()=>{setMode("reset");setMessage("")}}>Forgot password?</button></>}</div></div></section></main>
}
