"use client";
import { useState } from "react";
import { Activity, AlertCircle, ArrowRight } from "lucide-react";
import { getSupabaseBrowserClient,hasSupabaseConfig } from "@/lib/supabase";

export function AuthPanel(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"login"|"signup">("login"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase){setMessage("Authentication needs the Supabase environment variables listed below.");return}setBusy(true);setMessage("");const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback`}});setBusy(false);if(result.error)setMessage(result.error.message);else if(mode==="signup")setMessage("Check your email to confirm your account.");else location.href="/dashboard"}
 async function google(){const supabase=getSupabaseBrowserClient();if(!supabase){setMessage("Configure Supabase before enabling Google sign-in.");return}await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback`}})}
 return <main className="auth-page"><section className="auth-brand"><a className="brand" href="/"><span><Activity/></span>Prometric <b>Edge</b></a><div><span className="eyebrow">Welcome to your study plan</span><h1>Every session should move you closer to readiness.</h1><p>Save progress, identify weak topics and continue preparing from any device.</p></div></section><section className="auth-form"><div><h2>{mode==="login"?"Sign in":"Create your account"}</h2><p>{mode==="login"?"Continue your exam preparation.":"Start with free practice—no card required."}</p>{!hasSupabaseConfig&&<div className="config-alert"><AlertCircle/><span><b>Setup required</b> Add Supabase variables in Vercel to activate accounts.</span></div>}<button className="google-button" onClick={google}>Continue with Google</button><div className="or"><span/>or use email<span/></div><form onSubmit={submit}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters"/></label>{message&&<p className="form-message">{message}</p>}<button className="primary-button" disabled={busy}>{busy?"Please wait...":mode==="login"?"Sign in":"Create account"}<ArrowRight size={18}/></button></form><button className="switch-auth" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}}>{mode==="login"?"New to Prometric Edge? Create an account":"Already registered? Sign in"}</button></div></section></main>
}
