export type Profession = "pharmacist" | "nurse";
export type Question = {
  id:string; profession:Profession; topic:string; stem:string; options:string[];
  answer:number; explanation:string; level:"Application"|"Analysis"; skill:string;
};
type Row=[string,Profession,string,string,string[],number,string,Question["level"],string];

const r:Row[]=[
["p01","pharmacist","Cardiovascular Therapeutics","A 68-year-old taking warfarin for atrial fibrillation is prescribed trimethoprim-sulfamethoxazole. His latest INR is stable. What is the pharmacist's BEST action?",["Dispense and advise him to avoid all green vegetables","Withhold warfarin permanently","Contact the prescriber because the antibiotic may increase INR and bleeding risk","Advise taking both medicines two hours apart"],2,"Trimethoprim-sulfamethoxazole can substantially increase warfarin effect. The pharmacist should clarify therapy and arrange an appropriate monitoring or alternative plan; dose separation does not prevent the interaction.","Analysis","Interaction management"],
["p02","pharmacist","Patient Safety","A prescription reads methotrexate 10 mg orally once daily for rheumatoid arthritis. What should the pharmacist do FIRST?",["Dispense seven tablets for one week","Hold dispensing and urgently clarify the frequency","Change the medicine to folic acid","Ask the patient to take it only when pain is severe"],1,"Methotrexate for rheumatoid arthritis is normally dosed weekly. Daily dosing can cause fatal toxicity, so the prescription must be held and clarified before supply.","Analysis","Error interception"],
["p03","pharmacist","Calculations","A child weighing 18 kg is prescribed amoxicillin 30 mg/kg/day in three equal doses. The suspension is 250 mg/5 mL. How many millilitres should be given per dose?",["1.8 mL","3.6 mL","5.4 mL","10.8 mL"],1,"Daily dose is 540 mg; divided three times gives 180 mg per dose. At 50 mg/mL, 180 mg requires 3.6 mL.","Application","Dose calculation"],
["p04","pharmacist","Diabetes","A patient using basal-bolus insulin reports sweating and confusion before lunch. Capillary glucose is 2.8 mmol/L and the patient can swallow. What is the BEST immediate advice?",["Take the next insulin dose early","Consume 15–20 g of fast-acting carbohydrate and recheck glucose after about 15 minutes","Eat a high-fat meal and recheck tomorrow","Exercise to increase glucose use"],1,"Conscious hypoglycaemia is treated promptly with fast-acting carbohydrate, followed by reassessment and further treatment or longer-acting carbohydrate as needed.","Application","Acute management"],
["p05","pharmacist","Respiratory Therapeutics","A patient with asthma uses salbutamol several times daily and wakes with symptoms twice weekly. What is the pharmacist's BEST response?",["Reassure that frequent reliever use shows good control","Recommend doubling salbutamol without review","Assess adherence and inhaler technique, and refer for controller-treatment review","Advise stopping all inhalers for one week"],2,"Frequent reliever use and nocturnal symptoms suggest poor control and increased risk. Technique and adherence should be assessed and controller therapy reviewed.","Analysis","Therapy optimisation"],
["p06","pharmacist","Renal Dosing","An older adult with eGFR 24 mL/min is prescribed a usual adult dose of a medicine primarily eliminated unchanged by the kidneys. What principle should guide the pharmacist?",["Renal function is irrelevant in older adults","Verify whether dose or interval adjustment is required before dispensing","Automatically halve every medicine dose","Use body weight alone"],1,"Renally cleared medicines may accumulate when kidney function is reduced. Adjustment is medicine-specific and should be verified using an authoritative reference.","Application","Dose individualisation"],
["p07","pharmacist","Infectious Diseases","A patient asks for an antibiotic for three days of rhinorrhoea, sore throat and cough without red flags. What is the BEST response?",["Supply a broad-spectrum antibiotic","Explain likely viral illness, provide appropriate symptomatic advice and safety-netting","Recommend leftover antibiotics from a family member","Advise stopping fluids"],1,"Uncomplicated viral respiratory illness does not benefit from antibiotics. Symptom management, red-flag advice and antimicrobial stewardship are appropriate.","Application","Antimicrobial stewardship"],
["p08","pharmacist","Patient Safety","A patient presents prescriptions for sildenafil and sublingual nitroglycerin. What is the MOST important intervention?",["Advise taking them with food","Warn that concomitant use is contraindicated because of severe hypotension risk and contact the prescriber","Separate doses by one hour","Recommend an antacid"],1,"PDE-5 inhibitors and nitrates can produce profound, potentially life-threatening hypotension. The combination requires immediate intervention.","Application","Contraindication recognition"],
["p09","pharmacist","Calculations","A 1,000 mL infusion is prescribed over 8 hours through a set delivering 20 drops/mL. What is the closest required rate in drops per minute?",["21","30","42","125"],2,"1,000 × 20 = 20,000 drops. Dividing by 480 minutes gives 41.7, rounded to 42 drops/minute.","Application","Infusion calculation"],
["p10","pharmacist","Therapeutic Drug Monitoring","A patient receiving gentamicin develops rising serum creatinine. What is the pharmacist's BEST recommendation?",["Continue unchanged because efficacy is the only concern","Review dosing and timing of levels, hold or adjust therapy as clinically appropriate, and contact the team urgently","Add an NSAID for discomfort","Increase the dose to shorten treatment"],1,"Aminoglycosides are nephrotoxic and require renal-function and concentration-guided dosing. Deterioration warrants prompt reassessment.","Analysis","Monitoring interpretation"],
["p11","pharmacist","Dosage Forms","A patient with dysphagia asks to crush an enteric-coated tablet. What is the BEST response?",["Crush it into juice","Split it and chew both halves","Do not alter it; verify a suitable formulation or therapeutic alternative","Dissolve it in hot water"],2,"Crushing may destroy the release characteristics, reduce efficacy or increase toxicity. A pharmacist should identify an appropriate alternative.","Application","Formulation safety"],
["p12","pharmacist","Medication Safety","During final check, a label reads insulin 10U subcutaneously. What is the safest correction?",["Keep 10U because it is standard","Write 10 units in full","Change it to 10.0 units","Use IU instead"],1,"The abbreviation U can be misread as a zero. Writing units in full reduces tenfold dosing errors; trailing zeros should also be avoided.","Application","Safe notation"],
["p13","pharmacist","Endocrine Therapeutics","A patient has taken prednisolone daily for several months and wants to stop immediately because of weight gain. What is the BEST advice?",["Stop today","Double the dose for two days then stop","Explain the risk of adrenal insufficiency and arrange a supervised taper/review","Take it only when symptoms recur"],2,"Long-term systemic corticosteroids suppress the hypothalamic-pituitary-adrenal axis. Abrupt cessation may cause adrenal crisis.","Analysis","Withdrawal prevention"],
["p14","pharmacist","Transitions of Care","A patient is discharged with a list that omits a long-term anticonvulsant used before admission. What should the pharmacist do?",["Assume it was intentionally stopped","Reconcile the pre-admission, inpatient and discharge lists and clarify the discrepancy","Add every medicine used before admission","Wait until the next seizure"],1,"Medication reconciliation distinguishes intentional changes from errors and prevents harmful omissions, duplications and dosing discrepancies.","Analysis","Medication reconciliation"],
["p15","pharmacist","Calculations","Norepinephrine 4 mg is diluted to 250 mL. The prescribed rate is 0.08 microgram/kg/min for a 75 kg patient. What infusion rate is required?",["2.25 mL/h","11.25 mL/h","22.5 mL/h","37.5 mL/h"],2,"Dose is 6 micrograms/min or 360 micrograms/h. Concentration is 16 micrograms/mL, so the rate is 22.5 mL/h.","Analysis","Critical-care calculation"],
["p16","pharmacist","Cardiovascular Therapeutics","A patient taking metoprolol and insulin reports that hypoglycaemia now occurs without palpitations. Which explanation is MOST appropriate?",["Metoprolol causes hyperglycaemia only","Beta blockers may mask adrenergic warning symptoms, although sweating may remain","Insulin cannot cause hypoglycaemia","The glucose meter is necessarily faulty"],1,"Beta blockade can blunt tremor, tachycardia and palpitations, making hypoglycaemia harder to recognise.","Application","Adverse-effect counselling"],
["p17","pharmacist","Emergency Care","Minutes after taking an antibiotic, a patient develops generalized urticaria, wheeze and facial swelling. What is the priority?",["Recommend an oral antihistamine and send the patient home","Activate emergency response immediately; airway and breathing are threatened","Wait 30 minutes to confirm the diagnosis","Offer food and water"],1,"The presentation is compatible with anaphylaxis. Emergency treatment and airway/breathing support take priority.","Application","Emergency recognition"],
["p18","pharmacist","Storage & Quality","A refrigerator storing vaccines was recorded at 12°C for four hours. What is the BEST action?",["Use the vaccines quickly","Freeze them to restore potency","Quarantine the stock, document the excursion and obtain stability guidance before use","Discard all stock without assessment"],2,"Cold-chain excursions require quarantine, documentation and product-specific assessment. Products should not be used or discarded until evaluated.","Analysis","Cold-chain management"],
["p19","pharmacist","Toxicology","A patient taking digoxin reports nausea, yellow vision and new palpitations. What is the BEST response?",["Recommend another dose","Arrange urgent clinical assessment and review renal function, electrolytes, ECG and digoxin exposure","Suggest an antacid only","Reassure that this is expected"],1,"Gastrointestinal, visual and rhythm symptoms suggest digoxin toxicity, which may be life-threatening and requires urgent evaluation.","Analysis","Toxicity recognition"],
["p20","pharmacist","Ethics & UAE Practice","A relative requests the medication history of a competent adult patient who is not present. There is no consent or emergency. What should the pharmacist do?",["Disclose it because the requester is family","Protect confidentiality and disclose only with consent or another lawful basis","Provide only controlled-medicine information","Delete the record"],1,"Professional confidentiality applies unless the patient consents or a valid legal or safety basis permits disclosure.","Application","Confidentiality"],

["n01","nurse","Emergency & Adult Health","A 72-year-old with suspected infection has BP 86/52 mmHg, respiratory rate 30/min, new confusion and urine output 15 mL/hour. What should the nurse do FIRST?",["Recheck in four hours","Activate urgent sepsis/escalation response while supporting airway, breathing and circulation","Offer oral fluids only","Document and wait for rounds"],1,"Hypotension, tachypnoea, altered mentation and oliguria indicate organ dysfunction and possible septic shock. Immediate escalation and resuscitative assessment are required.","Analysis","Clinical prioritisation"],
["n02","nurse","Medication Safety","Before giving rapid-acting insulin, the nurse finds the meal has been delayed and glucose is 4.1 mmol/L. What is the BEST action?",["Give insulin and ask the patient to wait","Withhold temporarily and clarify timing according to the order and local protocol while arranging food","Double the dose with the meal","Document it as administered"],1,"Rapid-acting insulin without available carbohydrate may cause hypoglycaemia. Timing should be coordinated and deviations clarified.","Analysis","Medication timing"],
["n03","nurse","Infection Prevention","After caring for a patient with suspected Clostridioides difficile diarrhoea, which hand-hygiene method is MOST appropriate?",["Alcohol hand rub only","Soap and water after glove removal","No hand hygiene if gloves were intact","Wipe hands with a dry towel"],1,"Soap and water mechanically removes spores; gloves reduce exposure but never replace hand hygiene.","Application","Transmission prevention"],
["n04","nurse","Neurological Care","A patient suddenly develops aphasia and right-arm weakness. Symptoms began 25 minutes ago. What is the priority?",["Give oral fluids","Activate the stroke pathway, note last-known-well time and assess glucose/ABCs","Allow the patient to sleep","Wait for family consent before assessment"],1,"Time-critical stroke evaluation requires immediate pathway activation, accurate symptom timing and rapid exclusion of mimics such as hypoglycaemia.","Application","Time-critical escalation"],
["n05","nurse","Patient Safety","Two patients on the same ward have similar names. What is the safest method before medication administration?",["Use bed number and diagnosis","Ask another patient","Use two approved patient identifiers matched to the medication record","Identify by room location"],2,"Two approved identifiers reduce wrong-patient errors. Room and bed numbers are not reliable identifiers.","Application","Patient identification"],
["n06","nurse","Respiratory Care","A conscious patient with acute dyspnoea has SpO₂ 84% and cannot speak full sentences. What should the nurse do FIRST?",["Position upright, initiate the emergency assessment and provide oxygen according to protocol/order","Place flat and leave to obtain paperwork","Encourage walking","Give oral fluids"],0,"Severe hypoxaemia and distress require immediate ABC assessment, appropriate positioning, oxygen support and escalation.","Application","Airway and breathing"],
["n07","nurse","Occupational Safety","Immediately after a hollow-bore needlestick injury, what is the nurse's priority?",["Squeeze the wound aggressively","Wash the area, report immediately and follow the exposure-assessment pathway","Wait for symptoms","Hide the event to protect confidentiality"],1,"Prompt washing, reporting, source/risk assessment and timely post-exposure management are essential.","Application","Exposure management"],
["n08","nurse","Medication Safety","A handwritten medication order is illegible and the prescriber is temporarily unavailable. What is the safest action?",["Ask the patient what dose is usual and administer it","Clarify the order through the approved pathway before administration","Choose the lowest available dose","Omit it without documenting"],1,"The nurse must not guess. Ambiguous orders require clarification and appropriate documentation before administration.","Application","Order verification"],
["n09","nurse","Maternal Health","Twenty minutes after vaginal delivery, a patient has heavy bleeding, HR 124/min, BP 88/54 mmHg and a boggy uterus. What is the priority?",["Leave to obtain consent forms","Call the obstetric emergency response and initiate postpartum-haemorrhage measures within scope","Offer oral iron","Reassess after one hour"],1,"Uterine atony with haemodynamic compromise is an obstetric emergency requiring immediate coordinated response.","Analysis","Obstetric emergency"],
["n10","nurse","Endocrine Care","A patient with diabetes becomes sweaty, tremulous and confused. Bedside glucose is 2.5 mmol/L and the patient cannot swallow safely. What is the BEST action?",["Give oral juice","Follow the severe-hypoglycaemia protocol using an appropriate parenteral treatment and escalate","Administer more insulin","Wait for the next meal"],1,"An unsafe swallow makes oral carbohydrate hazardous. Severe hypoglycaemia requires protocol-based parenteral therapy and close reassessment.","Application","Acute glycaemic care"],
["n11","nurse","Falls & Mobility","An older inpatient is confused, weak and attempting to walk unassisted. Which intervention is BEST?",["Apply restraints routinely","Implement individualized fall precautions, address reversible causes and keep assistance/call bell available","Keep the room dark","Tell the patient never to move"],1,"Effective prevention is individualized, least restrictive and includes assessment, environmental controls and supervised mobility.","Analysis","Risk reduction"],
["n12","nurse","Infection Prevention","While providing perineal care, the nurse must then access the patient's IV line. What should the nurse do?",["Use the same gloves","Remove gloves, perform hand hygiene and apply clean gloves before the clean task","Wipe gloves with alcohol","Complete the IV task first with contaminated gloves"],1,"Moving from a contaminated to a clean task requires glove change and hand hygiene to prevent cross-contamination.","Application","Aseptic practice"],
["n13","nurse","Opioid Safety","A postoperative patient receiving opioids is difficult to arouse, with respirations 7/min and SpO₂ 82%. What is the priority?",["Give the next dose for pain","Stop opioid administration, call for urgent help and support airway/breathing according to protocol","Allow uninterrupted sleep","Document before assessing"],1,"Severe sedation and respiratory depression are immediately life-threatening. Airway, ventilation, escalation and reversal protocol take priority.","Application","Deterioration response"],
["n14","nurse","Ethics & Consent","A competent adult refuses a recommended blood transfusion after the risks and alternatives are explained. What is the nurse's BEST response?",["Administer it secretly","Respect the refusal, assess understanding, notify the responsible clinician and document appropriately","Ask family to override the decision","Remove the refusal from the record"],1,"A competent adult may refuse treatment. The nurse supports informed decision-making, escalation and accurate documentation.","Analysis","Patient autonomy"],
["n15","nurse","Neonatal Care","A newborn is centrally cyanosed and has grunting respirations. What should the nurse do FIRST?",["Continue routine feeding","Initiate newborn emergency assessment and call for immediate assistance","Wrap the infant and reassess tomorrow","Ask the parent to observe"],1,"Central cyanosis with respiratory distress indicates significant hypoxaemia and requires immediate neonatal resuscitative assessment.","Application","Neonatal deterioration"],
["n16","nurse","High-Alert Medicines","A second nurse is asked to independently check an IV heparin infusion. What does an effective independent check require?",["Repeat the first nurse's verbal calculation","Independently verify patient, order, concentration, calculation, pump settings and relevant monitoring","Check only the medicine name","Sign without viewing the pump"],1,"Independent verification must genuinely reassess critical elements rather than merely confirm another person's work.","Analysis","Independent verification"],
["n17","nurse","Electrolytes & Cardiac Care","A patient has muscle weakness, peaked T waves and serum potassium 6.8 mmol/L. What is the priority?",["Encourage potassium-rich foods","Place on cardiac monitoring and escalate urgently for hyperkalaemia management","Recheck next week","Give an oral potassium supplement"],1,"Severe hyperkalaemia with ECG changes can cause fatal arrhythmia and requires urgent monitored treatment.","Analysis","Critical-result response"],
["n18","nurse","Communication","During handover, which SBAR recommendation is MOST effective?",["The patient looks bad","Please review this patient now because BP has fallen to 82/50 despite the initial intervention","Read the whole record when free","No recommendation is necessary"],1,"A clear recommendation communicates urgency, the requested action and relevant clinical change.","Application","Escalation communication"],
["n19","nurse","Device-Associated Infection","Which action most effectively reduces catheter-associated urinary infection risk?",["Insert catheters for convenience","Use only for a valid indication, maintain a closed system and remove as early as possible","Disconnect the system daily","Keep the collection bag above bladder level"],1,"Avoiding unnecessary catheterization and early removal are central preventive measures; the closed system and dependent drainage must be maintained.","Application","Device safety"],
["n20","nurse","Quality & Accountability","A nurse discovers that the wrong dose was administered 20 minutes earlier. What should happen FIRST?",["Alter the medication record","Assess the patient and take immediate safety actions, then notify and report according to policy","Wait until shift change","Ask a colleague to accept responsibility"],1,"Patient assessment and harm mitigation come first. Transparent escalation, documentation and incident reporting follow.","Analysis","Post-error response"]
];

const rawQuestions:Question[]=r.map(([id,profession,topic,stem,options,answer,explanation,level,skill])=>({id,profession,topic,stem,options,answer,explanation,level,skill}));

const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const ids=new Set<string>();
const stems=new Set<string>();
for(const question of rawQuestions){
 if(ids.has(question.id)) throw new Error(`Duplicate question id: ${question.id}`);
 const fingerprint=`${question.profession}:${normalize(question.stem)}`;
 if(stems.has(fingerprint)) throw new Error(`Duplicate question stem: ${question.id}`);
 if(question.options.length!==4) throw new Error(`Question must have four options: ${question.id}`);
 if(question.answer<0||question.answer>=question.options.length) throw new Error(`Invalid answer index: ${question.id}`);
 ids.add(question.id);stems.add(fingerprint);
}
export const questions:Question[]=rawQuestions;

export const examTracks=[
 {slug:"pharmacist",title:"Gulf Pharmacist",subtitle:"DHA · DOH · MOHAP",questions:"20 simulation questions live",targetQuestions:450,time:"Timed simulation mode",accent:"amber"},
 {slug:"nurse",title:"Registered Nurse",subtitle:"DHA · DOH · MOHAP",questions:"20 simulation questions live",targetQuestions:450,time:"Timed simulation mode",accent:"mint"},
] as const;
